services:
  api:
    container_name: studia_api_dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DATABASE_URL : "root:Terserah123.@tcp(db:3306)/db_studia?parseTime=true"

  db :
    image: mysql:8.0
    container_name: studia_db_dev
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: Terserah123.
      MYSQL_DATABASE: db_studia 
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  frontend: 
    container_name: studia_frontend_dev
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api 

volumes:
  mysql-data:
    name: studia-mysql-data