FROM golang:1.24-alpine

RUN apk add --no-cache git build-base

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY .air.toml .

COPY go.mod go.sum ./

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]

